load correction_ratio_test_IF_ID_CF_random

plotCorrectionRatios_4lines(falsePrediction(:, 2:3), missedPrediction(:,2:3),...
    correctionR(:,2:3), avgResidual(:,2:3), range, Legends(2:3), ['cr_ID_CF_' Type],...
    colors(2:3), lineStyles(2:3), markers(2:3));

load correction_ratio_test_IF_ID_CF_random_degen.mat

plotCorrectionRatios_4lines(falsePrediction(:, 2:3), missedPrediction(:,2:3),...
    correctionR(:,2:3), avgResidual(:,2:3), range, Legends(2:3), ['cr_ID_CF_' Type],...
    colors(2:3), lineStyles(2:3), markers(2:3));
